/**
 * 角色与技能数据模型
 * 技能类型：damage | heal | buff_atk | debuff_def
 * target：enemy | ally | self
 */

// 运行时立绘：assets/ultraman_heroes / assets/ultraman_kaiju
// 经典角色扩充：初代 / 赛文 / 杰克（及佐菲）
// 中文名按素材文件名翻译；旧 SVG 不再作为运行时主素材

const SKILL_TYPES = {
  DAMAGE: "damage",
  DAMAGE_ALL: "damage_all",
  MULTI_HIT: "multi_hit",
  LIFESTEAL: "lifesteal",
  POISON: "poison",
  HEAL: "heal",
  HEAL_ALL: "heal_all",
  REVIVE: "revive",
  REVIVE_ALL: "revive_all",
  DODGE: "dodge",
  BUFF_ATK: "buff_atk",
  DEBUFF_DEF: "debuff_def",
};

const TARGET_TYPES = {
  ENEMY: "enemy",
  ALLY: "ally",
  SELF: "self",
  ALL_ENEMIES: "all_enemies",
  ALL_ALLIES: "all_allies",
  DEAD_ALLY: "dead_ally",
  ALL_DEAD_ALLIES: "all_dead_allies",
};

/** @type {Array<Object>} */
const HERO_ROSTER = [
  {
    id: "ultra_tiga",
    name: "迪迦奥特曼",
    title: "光之巨人",
    side: "hero",
    maxHp: 1180,
    atk: 145,
    def: 42,
    spd: 88,
    color: "#4fc3f7",
    image: "assets/ultraman_heroes/ULTRAMAN TIGA.png",
    skills: [
      { id: "basic", name: "光之拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础近战攻击" },
      { id: "zeperion", name: "泽佩利昂光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.75, cooldown: 2, desc: "强力光线，造成高额伤害" },
      { id: "light_heal", name: "光能治愈", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.ALLY, power: 0.55, cooldown: 3, desc: "恢复一名队友生命" },
    ],
  },
  {
    id: "ultra_original",
    name: "初代奥特曼",
    title: "光之国传说",
    side: "hero",
    maxHp: 1200,
    atk: 150,
    def: 46,
    spd: 86,
    color: "#e53935",
    image: "assets/ultraman_heroes/ULTRAMAN.jpg",
    skills: [
      { id: "basic", name: "斯派修姆拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "经典近战打击" },
      { id: "specium", name: "斯派修姆光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.8, cooldown: 2, desc: "十字手势必杀光线" },
      { id: "ultra_slash", name: "八分光轮", type: SKILL_TYPES.DEBUFF_DEF, target: TARGET_TYPES.ENEMY, power: 0.36, cooldown: 3, duration: 2, desc: "光轮破防，降低敌方防御" },
    ],
  },
  {
    id: "ultra_seven",
    name: "赛文奥特曼",
    title: "宇宙警备队",
    side: "hero",
    maxHp: 1120,
    atk: 138,
    def: 48,
    spd: 84,
    color: "#90caf9",
    image: "assets/ultraman_heroes/ULTRASEVEN.jpg",
    skills: [
      { id: "basic", name: "眼部光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础远程攻击" },
      { id: "emerium", name: "艾梅利姆光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.65, cooldown: 2, desc: "精准高伤技能" },
      { id: "shield_break", name: "破防射线", type: SKILL_TYPES.DEBUFF_DEF, target: TARGET_TYPES.ENEMY, power: 0.4, cooldown: 3, duration: 2, desc: "降低敌方防御 2 回合" },
    ],
  },
  {
    id: "ultra_jack",
    name: "杰克奥特曼",
    title: "归来的奥特曼",
    side: "hero",
    maxHp: 1150,
    atk: 148,
    def: 45,
    spd: 91,
    color: "#1e88e5",
    image: "assets/ultraman_heroes/ULTRAMAN JACK.jpg",
    skills: [
      { id: "basic", name: "斯派修姆斩", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础斩击" },
      { id: "ultra_bracelet", name: "奥特手镯", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.68, cooldown: 2, desc: "手镯变化攻击" },
      { id: "cinerama", name: "希奈拉玛光线", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.33, cooldown: 3, duration: 2, desc: "积蓄光能提升攻击" },
    ],
  },
  {
    id: "ultra_zoffy",
    name: "佐菲",
    title: "奥特兄弟队长",
    side: "hero",
    maxHp: 1180,
    atk: 142,
    def: 50,
    spd: 83,
    color: "#fb8c00",
    image: "assets/ultraman_heroes/ZOFFY.png",
    skills: [
      { id: "basic", name: "M87 拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础打击" },
      { id: "m87", name: "M87 光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.78, cooldown: 2, desc: "队长级强力光线" },
      { id: "command", name: "指挥号令", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.ALLY, power: 0.3, cooldown: 3, duration: 2, desc: "提升一名队友攻击" },
    ],
  },
  {
    id: "ultra_zero",
    name: "赛罗奥特曼",
    title: "新世代之光",
    side: "hero",
    maxHp: 1050,
    atk: 160,
    def: 36,
    spd: 102,
    color: "#81d4fa",
    image: "assets/ultraman_heroes/ULTRAMAN ZERO.jpg",
    skills: [
      { id: "basic", name: "高速踢击", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "快速基础攻击" },
      { id: "wide_shot", name: "宽幅光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.55, cooldown: 2, desc: "中高伤害光线" },
      { id: "zero_drive", name: "赛罗驱动", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.35, cooldown: 3, duration: 2, desc: "提升自身攻击 2 回合" },
    ],
  },
  {
    id: "ultra_geed",
    name: "捷德奥特曼",
    title: "融合上升",
    side: "hero",
    maxHp: 1080,
    atk: 150,
    def: 40,
    spd: 95,
    color: "#64b5f6",
    image: "assets/ultraman_heroes/ULTRAMAN GEED.jpg",
    skills: [
      { id: "basic", name: "融合拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "wreaking", name: "破坏冲击波", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.7, cooldown: 2, desc: "爆发伤害" },
      { id: "rally", name: "战意鼓舞", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.ALLY, power: 0.3, cooldown: 3, duration: 2, desc: "提升一名队友攻击" },
    ],
  },
  {
    id: "ultra_z",
    name: "泽塔奥特曼",
    title: "新生代之光",
    side: "hero",
    maxHp: 1100,
    atk: 142,
    def: 44,
    spd: 90,
    color: "#29b6f6",
    image: "assets/ultraman_heroes/ULTRAMAN Z.jpg",
    skills: [
      { id: "basic", name: "Z 斩击", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础斩击" },
      { id: "zestium", name: "泽斯提乌姆光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.8, cooldown: 3, desc: "超高伤害必杀" },
      { id: "mend", name: "光粒子修复", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.SELF, power: 0.45, cooldown: 2, desc: "自我恢复" },
    ],
  },
  {
    id: "ultra_cosmos",
    name: "高斯奥特曼",
    title: "蓝色和平",
    side: "hero",
    maxHp: 1200,
    atk: 130,
    def: 50,
    spd: 78,
    color: "#4dd0e1",
    image: "assets/ultraman_heroes/ULTRAMAN COSMOS.jpg",
    skills: [
      { id: "basic", name: "和平之拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "full_moon", name: "满月光环", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.ALLY, power: 0.65, cooldown: 3, desc: "强力治疗队友" },
      { id: "blaster", name: "高斯爆裂", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.5, cooldown: 2, desc: "稳定输出技能" },
    ],
  },
  {
    id: "ultra_dyna",
    name: "戴拿奥特曼",
    title: "未来之光",
    side: "hero",
    maxHp: 1140,
    atk: 148,
    def: 41,
    spd: 93,
    color: "#42a5f5",
    image: "assets/ultraman_heroes/ULTRAMAN DYNA.jpg",
    skills: [
      { id: "basic", name: "闪光拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "solgent", name: "索尔真特光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.68, cooldown: 2, desc: "强力光线" },
      { id: "strong_form", name: "强力形态", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.32, cooldown: 3, duration: 2, desc: "提升自身攻击" },
    ],
  },
  {
    id: "ultra_gaia",
    name: "盖亚奥特曼",
    title: "大地之光",
    side: "hero",
    maxHp: 1220,
    atk: 136,
    def: 54,
    spd: 80,
    color: "#26c6da",
    image: "assets/ultraman_heroes/ULTRAMAN GAIA.jpg",
    skills: [
      { id: "basic", name: "光子拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "quantum", name: "量子光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.6, cooldown: 2, desc: "稳定高伤" },
      { id: "earth_guard", name: "大地守护", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.ALLY, power: 0.5, cooldown: 3, desc: "恢复队友生命" },
    ],
  },
  {
    id: "ultra_mebius",
    name: "梦比优斯",
    title: "继承之光",
    side: "hero",
    maxHp: 1090,
    atk: 146,
    def: 43,
    spd: 96,
    color: "#5c6bc0",
    image: "assets/ultraman_heroes/ULTRAMAN MEBIUS.jpg",
    skills: [
      { id: "basic", name: "梦比优斯拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "mebius_ray", name: "梦比优斯光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.66, cooldown: 2, desc: "强力光线" },
      { id: "courage", name: "燃烧勇气", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.ALLY, power: 0.28, cooldown: 3, duration: 2, desc: "鼓舞队友攻击" },
    ],
  },
  {
    id: "ultra_orb",
    name: "欧布奥特曼",
    title: "源气之光",
    side: "hero",
    maxHp: 1110,
    atk: 152,
    def: 39,
    spd: 97,
    color: "#7e57c2",
    image: "assets/ultraman_heroes/ULTRAMAN ORB.jpg",
    skills: [
      { id: "basic", name: "欧布斩", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础斩击" },
      { id: "orb_ray", name: "欧布终极光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.72, cooldown: 2, desc: "爆发伤害" },
      { id: "origin", name: "源气增幅", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.34, cooldown: 3, duration: 2, desc: "提升自身攻击" },
    ],
  },
  {
    id: "ultra_taro",
    name: "泰罗奥特曼",
    title: "奥特六兄弟",
    side: "hero",
    maxHp: 1160,
    atk: 144,
    def: 47,
    spd: 86,
    color: "#ef6c00",
    image: "assets/ultraman_heroes/ULTRAMAN TARO.jpg",
    skills: [
      { id: "basic", name: "斯托利姆拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "storium", name: "斯托利姆光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.7, cooldown: 2, desc: "强力光线" },
      { id: "badge", name: "奥特徽章", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.SELF, power: 0.48, cooldown: 2, desc: "自我恢复" },
    ],
  },
  {
    id: "ultra_leo",
    name: "雷欧奥特曼",
    title: "宇宙拳王",
    side: "hero",
    maxHp: 1070,
    atk: 168,
    def: 35,
    spd: 104,
    color: "#ff7043",
    image: "assets/ultraman_heroes/ULTRAMAN LEO.jpg",
    skills: [
      { id: "basic", name: "雷欧踢", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础踢击" },
      { id: "leo_kick", name: "雷欧飞踢", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.7, cooldown: 2, desc: "高伤踢技" },
      { id: "armor_break", name: "破甲连击", type: SKILL_TYPES.DEBUFF_DEF, target: TARGET_TYPES.ENEMY, power: 0.38, cooldown: 3, duration: 2, desc: "降低敌方防御" },
    ],
  },
  {
    id: "ultra_ace",
    name: "艾斯奥特曼",
    title: "光线王牌",
    side: "hero",
    maxHp: 1130,
    atk: 154,
    def: 43,
    spd: 92,
    color: "#ef5350",
    image: "assets/ultraman_heroes/ULTRAMAN ACE.jpg",
    skills: [
      { id: "metalium_fist", name: "梅塔利姆拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础近战攻击" },
      { id: "metalium_ray", name: "梅塔利姆光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.76, cooldown: 2, desc: "招牌必杀光线" },
      { id: "guillotine", name: "断头刀", type: SKILL_TYPES.DEBUFF_DEF, target: TARGET_TYPES.ENEMY, power: 0.38, cooldown: 3, duration: 2, desc: "削弱目标防御" },
    ],
  },
  {
    id: "ultra_ginga",
    name: "银河奥特曼",
    title: "未来之星",
    side: "hero",
    maxHp: 1110,
    atk: 149,
    def: 41,
    spd: 99,
    color: "#7e57c2",
    image: "assets/ultraman_heroes/ULTRAMAN GINGA.jpg",
    skills: [
      { id: "ginga_punch", name: "银河拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础光能打击" },
      { id: "cross_shoot", name: "银河十字光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.7, cooldown: 2, desc: "贯穿型强力光线" },
      { id: "star_barrier", name: "星光屏障", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.SELF, power: 0.46, cooldown: 3, desc: "恢复自身生命" },
    ],
  },
  {
    id: "ultra_nexus",
    name: "奈克瑟斯奥特曼",
    title: "羁绊之光",
    side: "hero",
    maxHp: 1060,
    atk: 158,
    def: 37,
    spd: 103,
    color: "#ffb74d",
    image: "assets/ultraman_heroes/ULTRAMAN NEXUS.jpg",
    skills: [
      { id: "nexus_elbow", name: "肘击", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "快速近身打击" },
      { id: "cross_ray", name: "十字风暴", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.82, cooldown: 3, desc: "高伤害终结光线" },
      { id: "meta_field", name: "美塔领域", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.34, cooldown: 3, duration: 2, desc: "提升自身攻击" },
    ],
  },
  {
    id: "ultra_blazar",
    name: "布莱泽奥特曼",
    title: "野性战士",
    side: "hero",
    maxHp: 1170,
    atk: 153,
    def: 45,
    spd: 94,
    color: "#26a69a",
    image: "assets/ultraman_heroes/ULTRAMAN BLAZAR.jpg",
    skills: [
      { id: "blazar_claw", name: "布莱泽爪", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "野性爪击" },
      { id: "spiral_burrade", name: "螺旋光刃", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.74, cooldown: 2, desc: "投掷旋转光刃" },
      { id: "wild_roar", name: "野性咆哮", type: SKILL_TYPES.DEBUFF_DEF, target: TARGET_TYPES.ENEMY, power: 0.34, cooldown: 3, duration: 2, desc: "压制目标防御" },
    ],
  },
  {
    id: "ultra_arc",
    name: "亚刻奥特曼",
    title: "想象之光",
    side: "hero",
    maxHp: 1100,
    atk: 151,
    def: 40,
    spd: 101,
    color: "#00acc1",
    image: "assets/ultraman_heroes/ULTRAMAN ARC.jpg",
    skills: [
      { id: "arc_punch", name: "亚刻拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础格斗攻击" },
      { id: "arc_final", name: "亚刻终结光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.78, cooldown: 2, desc: "想象力凝聚光线" },
      { id: "imagination", name: "想象增幅", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.ALLY, power: 0.3, cooldown: 3, duration: 2, desc: "提升一名队友攻击" },
    ],
  },
  {
    id: "ultra_father",
    name: "奥特之父",
    title: "宇宙警备队大队长",
    side: "hero",
    maxHp: 1300,
    atk: 148,
    def: 58,
    spd: 76,
    color: "#d6a236",
    image: "assets/ultraman_heroes/FATHER OF ULTRA.png",
    skills: [
      { id: "father_punch", name: "父亲之拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "沉稳的基础打击" },
      { id: "father_shot", name: "父亲光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.72, cooldown: 2, desc: "大队长级光线攻击" },
      { id: "father_guard", name: "警备队守护", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.ALLY, power: 0.52, cooldown: 3, desc: "恢复一名队友生命" },
    ],
  },
  {
    id: "ultra_mother",
    name: "奥特之母",
    title: "银十字军队长",
    side: "hero",
    maxHp: 1190,
    atk: 122,
    def: 52,
    spd: 84,
    color: "#ec6c9d",
    image: "assets/ultraman_heroes/MOTHER OF ULTRA.png",
    skills: [
      { id: "mother_light", name: "母亲光芒", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础光能攻击" },
      { id: "mother_heal", name: "玛丽治愈", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.ALLY, power: 0.68, cooldown: 3, desc: "强力恢复队友生命" },
      { id: "silver_cross", name: "银十字祝福", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.ALLY, power: 0.28, cooldown: 3, duration: 2, desc: "提升一名队友攻击" },
    ],
  },
  {
    id: "ultra_blu",
    name: "布鲁奥特曼",
    title: "水之战士",
    side: "hero",
    maxHp: 1090,
    atk: 145,
    def: 42,
    spd: 98,
    color: "#3f9dff",
    image: "assets/ultraman_heroes/ULTRAMAN BLU.jpg",
    skills: [
      { id: "aqua_punch", name: "跃水拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "迅捷的水流打击" },
      { id: "aqua_stream", name: "跃水射线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.68, cooldown: 2, desc: "凝聚水能光线" },
      { id: "aqua_mend", name: "清泉修复", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.SELF, power: 0.45, cooldown: 3, desc: "恢复自身生命" },
    ],
  },
  {
    id: "ultra_rosso",
    name: "罗索奥特曼",
    title: "火之战士",
    side: "hero",
    maxHp: 1120,
    atk: 156,
    def: 40,
    spd: 95,
    color: "#f05b4f",
    image: "assets/ultraman_heroes/ULTRAMAN ROSSO.jpg",
    skills: [
      { id: "flame_punch", name: "烈火拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "燃烧的基础攻击" },
      { id: "flame_stream", name: "烈火射线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.75, cooldown: 2, desc: "高温火焰光线" },
      { id: "flame_boost", name: "火焰增幅", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.34, cooldown: 3, duration: 2, desc: "提升自身攻击" },
    ],
  },
  {
    id: "ultra_x",
    name: "艾克斯奥特曼",
    title: "数据之光",
    side: "hero",
    maxHp: 1130,
    atk: 151,
    def: 43,
    spd: 97,
    color: "#39b7e5",
    image: "assets/ultraman_heroes/ULTRAMAN X.jpg",
    skills: [
      { id: "x_slash", name: "艾克斯斩", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "数据能量斩击" },
      { id: "xanadium", name: "扎纳帝姆光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.76, cooldown: 2, desc: "高能数据光线" },
      { id: "cyber_armor", name: "赛博装甲", type: SKILL_TYPES.DEBUFF_DEF, target: TARGET_TYPES.ENEMY, power: 0.35, cooldown: 3, duration: 2, desc: "干扰目标防御" },
    ],
  },
];

/** @type {Array<Object>} */
// Each hero keeps its basic attack and signature beam, while the third skill now
// showcases one of the expanded battle mechanics.
const HERO_SKILL_UPGRADES = {
  ultra_tiga: { id: "tiga_light_wave", name: "哉佩利敖光雨", type: SKILL_TYPES.DAMAGE_ALL, target: TARGET_TYPES.ALL_ENEMIES, power: 0.66, cooldown: 4, desc: "光雨攻击所有怪兽" },
  ultra_original: { id: "original_guard", name: "奥特屏障", type: SKILL_TYPES.DODGE, target: TARGET_TYPES.SELF, power: 0.55, cooldown: 4, duration: 2, desc: "获得闪避，躲开一次攻击" },
  ultra_seven: { id: "seven_combo", name: "头镖连击", type: SKILL_TYPES.MULTI_HIT, target: TARGET_TYPES.ENEMY, power: 0.56, hits: 3, cooldown: 3, desc: "连续命中同一目标 3 次" },
  ultra_jack: { id: "jack_sweep", name: "手镯光轮阵", type: SKILL_TYPES.DAMAGE_ALL, target: TARGET_TYPES.ALL_ENEMIES, power: 0.62, cooldown: 4, desc: "光轮横扫所有怪兽" },
  ultra_zoffy: { id: "zoffy_order", name: "M87 齐射", type: SKILL_TYPES.DAMAGE_ALL, target: TARGET_TYPES.ALL_ENEMIES, power: 0.64, cooldown: 4, desc: "队长级群体光线" },
  ultra_zero: { id: "zero_rush", name: "赛罗极速连段", type: SKILL_TYPES.MULTI_HIT, target: TARGET_TYPES.ENEMY, power: 0.52, hits: 4, cooldown: 4, desc: "高速四连踢" },
  ultra_geed: { id: "geed_absorb", name: "融合吸能", type: SKILL_TYPES.LIFESTEAL, target: TARGET_TYPES.ENEMY, power: 1.18, lifeSteal: 0.48, cooldown: 3, desc: "造成伤害并吸收生命" },
  ultra_z: { id: "z_revive", name: "泽斯蒂姆再起", type: SKILL_TYPES.REVIVE, target: TARGET_TYPES.DEAD_ALLY, power: 0.38, cooldown: 5, desc: "复活一名倒下的队友" },
  ultra_cosmos: { id: "cosmos_moon", name: "满月群愈", type: SKILL_TYPES.HEAL_ALL, target: TARGET_TYPES.ALL_ALLIES, power: 0.3, cooldown: 4, desc: "为全体队友恢复生命" },
  ultra_dyna: { id: "dyna_flash", name: "闪亮突袭", type: SKILL_TYPES.MULTI_HIT, target: TARGET_TYPES.ENEMY, power: 0.58, hits: 3, cooldown: 3, desc: "高速三连闪击" },
  ultra_gaia: { id: "gaia_rebirth", name: "大地复苏", type: SKILL_TYPES.REVIVE_ALL, target: TARGET_TYPES.ALL_DEAD_ALLIES, power: 0.28, cooldown: 6, desc: "复活所有倒下的队友" },
  ultra_mebius: { id: "mebius_burn", name: "炽热火环", type: SKILL_TYPES.POISON, target: TARGET_TYPES.ENEMY, power: 0.08, cooldown: 3, duration: 3, desc: "施加持续灼烧伤害" },
  ultra_orb: { id: "orb_hurricane", name: "欧布飓风", type: SKILL_TYPES.DAMAGE_ALL, target: TARGET_TYPES.ALL_ENEMIES, power: 0.65, cooldown: 4, desc: "飓风光线攻击全体" },
  ultra_taro: { id: "taro_fire", name: "斯特利姆吸收", type: SKILL_TYPES.LIFESTEAL, target: TARGET_TYPES.ENEMY, power: 1.14, lifeSteal: 0.45, cooldown: 3, desc: "吸收敌方能量恢复生命" },
  ultra_leo: { id: "leo_combo", name: "雷欧飞踢连招", type: SKILL_TYPES.MULTI_HIT, target: TARGET_TYPES.ENEMY, power: 0.6, hits: 3, cooldown: 3, desc: "强力三段飞踢" },
  ultra_ace: { id: "ace_guillotine", name: "断头刀风暴", type: SKILL_TYPES.DAMAGE_ALL, target: TARGET_TYPES.ALL_ENEMIES, power: 0.64, cooldown: 4, desc: "群体光刃攻击" },
  ultra_ginga: { id: "ginga_heal", name: "银河星光治愈", type: SKILL_TYPES.HEAL_ALL, target: TARGET_TYPES.ALL_ALLIES, power: 0.28, cooldown: 4, desc: "星光恢复全队生命" },
  ultra_nexus: { id: "nexus_dodge", name: "美塔领域闪避", type: SKILL_TYPES.DODGE, target: TARGET_TYPES.SELF, power: 0.6, cooldown: 4, duration: 2, desc: "展开领域并闪避攻击" },
  ultra_blazar: { id: "blazar_bleed", name: "螺旋光刃灼伤", type: SKILL_TYPES.POISON, target: TARGET_TYPES.ENEMY, power: 0.09, cooldown: 3, duration: 3, desc: "令目标持续受到灼伤" },
  ultra_arc: { id: "arc_imagine", name: "想象力齐射", type: SKILL_TYPES.DAMAGE_ALL, target: TARGET_TYPES.ALL_ENEMIES, power: 0.63, cooldown: 4, desc: "想象光弹攻击所有敌人" },
  ultra_father: { id: "father_revival", name: "父亲之光复苏", type: SKILL_TYPES.REVIVE, target: TARGET_TYPES.DEAD_ALLY, power: 0.42, cooldown: 5, desc: "复活一名队友并恢复生命" },
  ultra_mother: { id: "mother_grace", name: "母亲银十字", type: SKILL_TYPES.REVIVE_ALL, target: TARGET_TYPES.ALL_DEAD_ALLIES, power: 0.3, cooldown: 6, desc: "复活所有倒下的队友" },
  ultra_blu: { id: "blu_tide", name: "跃水群疗", type: SKILL_TYPES.HEAL_ALL, target: TARGET_TYPES.ALL_ALLIES, power: 0.27, cooldown: 4, desc: "水流治愈全体队友" },
  ultra_rosso: { id: "rosso_burn", name: "烈焰灼烧", type: SKILL_TYPES.POISON, target: TARGET_TYPES.ENEMY, power: 0.1, cooldown: 3, duration: 3, desc: "烈焰持续灼烧目标" },
  ultra_x: { id: "x_multi", name: "艾克斯数据连斩", type: SKILL_TYPES.MULTI_HIT, target: TARGET_TYPES.ENEMY, power: 0.55, hits: 3, cooldown: 3, desc: "数据之刃三连斩" },
};

HERO_ROSTER.forEach((hero) => {
  const upgrade = HERO_SKILL_UPGRADES[hero.id];
  if (upgrade) hero.skills[2] = upgrade;
});

const MONSTER_ROSTER = [
  {
    id: "kaiju_gomora",
    name: "哥莫拉",
    title: "古代怪兽",
    side: "monster",
    maxHp: 1250,
    atk: 148,
    def: 52,
    spd: 70,
    color: "#ef5350",
    image: "assets/ultraman_kaiju/GOMORA (1).jpg",
    skills: [
      { id: "basic", name: "角击", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础冲撞" },
      { id: "super_oscillo", name: "超振荡波", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.6, cooldown: 2, desc: "高伤震荡攻击" },
      { id: "harden", name: "岩甲硬化", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.25, cooldown: 3, duration: 2, desc: "提升自身攻击" },
    ],
  },
  {
    id: "kaiju_redking",
    name: "红王",
    title: "怪力怪兽",
    side: "monster",
    maxHp: 1180,
    atk: 165,
    def: 38,
    spd: 76,
    color: "#e53935",
    image: "assets/ultraman_kaiju/RED KING II.jpg",
    skills: [
      { id: "basic", name: "重拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础重击" },
      { id: "power_bomb", name: "怪力投摔", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.75, cooldown: 2, desc: "爆发物理伤害" },
      { id: "intimidate", name: "威吓咆哮", type: SKILL_TYPES.DEBUFF_DEF, target: TARGET_TYPES.ENEMY, power: 0.35, cooldown: 3, duration: 2, desc: "降低目标防御" },
    ],
  },
  {
    id: "kaiju_eleking",
    name: "艾雷王",
    title: "电流怪兽",
    side: "monster",
    maxHp: 1100,
    atk: 140,
    def: 40,
    spd: 92,
    color: "#ff7043",
    image: "assets/ultraman_kaiju/ELEKING.jpg",
    skills: [
      { id: "basic", name: "电击尾", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础电击" },
      { id: "thunder", name: "百万伏特", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.7, cooldown: 2, desc: "强力电流" },
      { id: "spark_heal", name: "电荷再生", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.SELF, power: 0.4, cooldown: 3, desc: "自我恢复" },
    ],
  },
  {
    id: "kaiju_zetton",
    name: "杰顿",
    title: "宇宙恐龙",
    side: "monster",
    maxHp: 1220,
    atk: 155,
    def: 46,
    spd: 80,
    color: "#d32f2f",
    image: "assets/ultraman_kaiju/ZETTON (1).jpg",
    skills: [
      { id: "basic", name: "火球", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础火球" },
      { id: "one_trillion", name: "一兆度火球", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.85, cooldown: 3, desc: "超高伤害必杀" },
      { id: "barrier_break", name: "屏障瓦解", type: SKILL_TYPES.DEBUFF_DEF, target: TARGET_TYPES.ENEMY, power: 0.45, cooldown: 3, duration: 2, desc: "大幅降低防御" },
    ],
  },
  {
    id: "kaiju_alien_baltan",
    name: "巴尔坦星人",
    title: "宇宙忍者",
    side: "monster",
    maxHp: 1000,
    atk: 135,
    def: 34,
    spd: 110,
    color: "#ff8a65",
    image: "assets/ultraman_kaiju/ALIEN BALTAN (1).jpg",
    skills: [
      { id: "basic", name: "钳子斩", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "white_destroy", name: "白色破坏光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.55, cooldown: 2, desc: "快速高伤" },
      { id: "clone_boost", name: "分身增幅", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.4, cooldown: 3, duration: 2, desc: "大幅提升攻击" },
    ],
  },
  {
    id: "kaiju_king_joe",
    name: "金古桥",
    title: "机器人军团",
    side: "monster",
    maxHp: 1300,
    atk: 132,
    def: 58,
    spd: 68,
    color: "#c62828",
    image: "assets/ultraman_kaiju/KING JOE.jpg",
    skills: [
      { id: "basic", name: "金属拳", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "pedanium", name: "佩达尼姆射线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.6, cooldown: 2, desc: "装甲射线" },
      { id: "repair", name: "自修复协议", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.ALLY, power: 0.5, cooldown: 3, desc: "修复一名队友" },
    ],
  },
  {
    id: "kaiju_belial",
    name: "贝利亚",
    title: "黑暗奥特曼",
    side: "monster",
    maxHp: 1240,
    atk: 170,
    def: 42,
    spd: 94,
    color: "#8e24aa",
    image: "assets/ultraman_kaiju/ULTRAMAN BELIAL.jpg",
    skills: [
      { id: "basic", name: "暗黑爪击", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "deathcium", name: "死灭光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.8, cooldown: 3, desc: "超高伤害必杀" },
      { id: "dark_boost", name: "黑暗增幅", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.36, cooldown: 3, duration: 2, desc: "提升自身攻击" },
    ],
  },
  {
    id: "kaiju_tyrant",
    name: "泰兰特",
    title: "合成怪兽",
    side: "monster",
    maxHp: 1280,
    atk: 158,
    def: 50,
    spd: 72,
    color: "#6d4c41",
    image: "assets/ultraman_kaiju/TYRANT.jpg",
    skills: [
      { id: "basic", name: "合成重击", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "flame", name: "火焰喷射", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.68, cooldown: 2, desc: "强力火焰" },
      { id: "roar", name: "威压咆哮", type: SKILL_TYPES.DEBUFF_DEF, target: TARGET_TYPES.ENEMY, power: 0.4, cooldown: 3, duration: 2, desc: "降低目标防御" },
    ],
  },
  {
    id: "kaiju_bemstar",
    name: "贝姆斯塔",
    title: "宇宙怪兽",
    side: "monster",
    maxHp: 1150,
    atk: 138,
    def: 48,
    spd: 82,
    color: "#00897b",
    image: "assets/ultraman_kaiju/BEMSTAR.png",
    skills: [
      { id: "basic", name: "吸能冲击", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "reflect", name: "能量反弹", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.58, cooldown: 2, desc: "反弹能量攻击" },
      { id: "absorb", name: "能量吸收", type: SKILL_TYPES.HEAL, target: TARGET_TYPES.SELF, power: 0.42, cooldown: 3, desc: "吸收能量恢复自身" },
    ],
  },
  {
    id: "kaiju_mefilas",
    name: "美菲拉斯星人",
    title: "策谋星人",
    side: "monster",
    maxHp: 1040,
    atk: 142,
    def: 36,
    spd: 108,
    color: "#5e35b1",
    image: "assets/ultraman_kaiju/ALIEN MEFILAS.jpg",
    skills: [
      { id: "basic", name: "精神冲击", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "hypno", name: "催眠光线", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.52, cooldown: 2, desc: "精神系伤害" },
      { id: "scheme", name: "谋略削弱", type: SKILL_TYPES.DEBUFF_DEF, target: TARGET_TYPES.ENEMY, power: 0.42, cooldown: 3, duration: 2, desc: "降低目标防御" },
    ],
  },
  {
    id: "kaiju_black_king",
    name: "黑王",
    title: "凶暴怪兽",
    side: "monster",
    maxHp: 1260,
    atk: 160,
    def: 49,
    spd: 74,
    color: "#37474f",
    image: "assets/ultraman_kaiju/BLACK KING.jpg",
    skills: [
      { id: "basic", name: "蛮力冲撞", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "horn", name: "角刺突进", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.7, cooldown: 2, desc: "强力冲锋" },
      { id: "berserk", name: "狂暴化", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.3, cooldown: 3, duration: 2, desc: "提升自身攻击" },
    ],
  },
  {
    id: "kaiju_twintail",
    name: "双尾怪",
    title: "古代怪兽",
    side: "monster",
    maxHp: 1120,
    atk: 146,
    def: 41,
    spd: 98,
    color: "#f4511e",
    image: "assets/ultraman_kaiju/TWINTAIL.png",
    skills: [
      { id: "basic", name: "双尾鞭击", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "sting", name: "毒刺突袭", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1.56, cooldown: 2, desc: "快速高伤" },
      { id: "swift", name: "迅捷强化", type: SKILL_TYPES.BUFF_ATK, target: TARGET_TYPES.SELF, power: 0.28, cooldown: 3, duration: 2, desc: "提升自身攻击" },
    ],
  },
];

function createExtraMonster({ id, name, title, hp, atk, def, spd, color, image, attackName, attackPower, special }) {
  return {
    id,
    name,
    title,
    side: "monster",
    maxHp: hp,
    atk,
    def,
    spd,
    color,
    image: `assets/ultraman_kaiju/${image}`,
    skills: [
      { id: "basic", name: "怪兽重击", type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: 1, cooldown: 0, desc: "基础攻击" },
      { id: "signature", name: attackName, type: SKILL_TYPES.DAMAGE, target: TARGET_TYPES.ENEMY, power: attackPower, cooldown: 2, desc: "怪兽招牌攻击" },
      special,
    ],
  };
}

MONSTER_ROSTER.push(
  createExtraMonster({ id: "kaiju_gomora", name: "哥莫拉", title: "古代怪兽", hp: 1260, atk: 152, def: 50, spd: 78, color: "#8d6e63", image: "GOMORA (1).jpg", attackName: "超振动波", attackPower: 1.68, special: { id: "tail_sweep", name: "尾部横扫", type: SKILL_TYPES.DAMAGE_ALL, target: TARGET_TYPES.ALL_ENEMIES, power: 0.58, cooldown: 4, desc: "攻击所有奥特曼" } }),
  createExtraMonster({ id: "kaiju_kingjoe", name: "金古桥", title: "宇宙机器人", hp: 1320, atk: 148, def: 60, spd: 72, color: "#90a4ae", image: "KING JOE.jpg", attackName: "佩丹尼姆炮", attackPower: 1.7, special: { id: "barrier", name: "分离闪避", type: SKILL_TYPES.DODGE, target: TARGET_TYPES.SELF, power: 0.55, cooldown: 4, duration: 2, desc: "分离机体躲开攻击" } }),
  createExtraMonster({ id: "kaiju_bemstar", name: "贝姆斯塔", title: "宇宙大怪兽", hp: 1200, atk: 145, def: 48, spd: 82, color: "#7e8b63", image: "BEMSTAR.png", attackName: "吸能冲击", attackPower: 1.62, special: { id: "energy_drain", name: "能量吞噬", type: SKILL_TYPES.LIFESTEAL, target: TARGET_TYPES.ENEMY, power: 1.12, lifeSteal: 0.45, cooldown: 3, desc: "吸收伤害转化为生命" } }),
  createExtraMonster({ id: "kaiju_tyrant", name: "泰兰特", title: "暴君怪兽", hp: 1450, atk: 160, def: 55, spd: 68, color: "#6d4c41", image: "TYRANT.jpg", attackName: "流星锤", attackPower: 1.78, special: { id: "tyrant_barrage", name: "暴君乱击", type: SKILL_TYPES.MULTI_HIT, target: TARGET_TYPES.ENEMY, power: 0.5, hits: 4, cooldown: 4, desc: "连续四次重击" } }),
  createExtraMonster({ id: "kaiju_melba", name: "美尔巴", title: "超古代龙", hp: 1080, atk: 150, def: 38, spd: 108, color: "#8e24aa", image: "MELBA.jpg", attackName: "美尔巴光线", attackPower: 1.64, special: { id: "dark_poison", name: "黑暗毒雾", type: SKILL_TYPES.POISON, target: TARGET_TYPES.ENEMY, power: 0.08, cooldown: 3, duration: 3, desc: "施加持续中毒" } }),
  createExtraMonster({ id: "kaiju_gomess", name: "哥美斯", title: "古代怪兽", hp: 1180, atk: 146, def: 47, spd: 80, color: "#795548", image: "GOMESS.jpg", attackName: "撕裂爪", attackPower: 1.66, special: { id: "toxic_claw", name: "剧毒爪痕", type: SKILL_TYPES.POISON, target: TARGET_TYPES.ENEMY, power: 0.07, cooldown: 3, duration: 3, desc: "令目标持续中毒" } }),
  createExtraMonster({ id: "kaiju_doragory", name: "多拉格里", title: "异次元超兽", hp: 1240, atk: 154, def: 46, spd: 86, color: "#ff8f00", image: "DORAGORY.jpg", attackName: "双翼切割", attackPower: 1.7, special: { id: "wing_storm", name: "翼刃风暴", type: SKILL_TYPES.DAMAGE_ALL, target: TARGET_TYPES.ALL_ENEMIES, power: 0.6, cooldown: 4, desc: "翼刃攻击全体" } }),
  createExtraMonster({ id: "kaiju_birdon", name: "巴顿", title: "火山怪鸟", hp: 1160, atk: 156, def: 42, spd: 96, color: "#e65100", image: "BIRDON.jpg", attackName: "火焰鸟喙", attackPower: 1.68, special: { id: "birdon_fire", name: "火毒羽粉", type: SKILL_TYPES.POISON, target: TARGET_TYPES.ENEMY, power: 0.09, cooldown: 3, duration: 3, desc: "火毒持续灼烧" } }),
  createExtraMonster({ id: "kaiju_pandon", name: "庞顿", title: "双头怪兽", hp: 1280, atk: 150, def: 52, spd: 74, color: "#bf360c", image: "PANDON.jpg", attackName: "双头火焰", attackPower: 1.72, special: { id: "pandon_combo", name: "双头连喷", type: SKILL_TYPES.MULTI_HIT, target: TARGET_TYPES.ENEMY, power: 0.54, hits: 3, cooldown: 3, desc: "双头三连喷射" } }),
  createExtraMonster({ id: "kaiju_jumbo_king", name: "詹伯王", title: "合体超兽", hp: 1420, atk: 158, def: 56, spd: 70, color: "#5d4037", image: "JUMBO KING.jpg", attackName: "地狱火焰", attackPower: 1.76, special: { id: "jumbo_absorb", name: "怨念吸收", type: SKILL_TYPES.LIFESTEAL, target: TARGET_TYPES.ENEMY, power: 1.15, lifeSteal: 0.42, cooldown: 3, desc: "造成伤害并恢复生命" } }),
  createExtraMonster({ id: "kaiju_baraba", name: "巴拉巴", title: "异次元超兽", hp: 1230, atk: 151, def: 49, spd: 84, color: "#6a1b9a", image: "BARABA.jpg", attackName: "镰刀导弹", attackPower: 1.69, special: { id: "baraba_rain", name: "导弹雨", type: SKILL_TYPES.DAMAGE_ALL, target: TARGET_TYPES.ALL_ENEMIES, power: 0.59, cooldown: 4, desc: "导弹覆盖全体敌人" } }),
  createExtraMonster({ id: "kaiju_antlar", name: "安特拉", title: "磁力怪兽", hp: 1210, atk: 147, def: 53, spd: 76, color: "#a1887f", image: "ANTLAR.jpg", attackName: "磁力钳击", attackPower: 1.67, special: { id: "sand_dodge", name: "沙暴潜行", type: SKILL_TYPES.DODGE, target: TARGET_TYPES.SELF, power: 0.58, cooldown: 4, duration: 2, desc: "潜入沙暴获得闪避" } }),
  createExtraMonster({ id: "kaiju_kemular", name: "凯姆拉", title: "毒气怪兽", hp: 1090, atk: 143, def: 40, spd: 102, color: "#689f38", image: "KEMULAR.jpg", attackName: "毒气冲撞", attackPower: 1.6, special: { id: "kemular_poison", name: "毒气喷射", type: SKILL_TYPES.POISON, target: TARGET_TYPES.ENEMY, power: 0.1, cooldown: 3, duration: 3, desc: "喷射持续毒气" } }),
  createExtraMonster({ id: "kaiju_kanegon", name: "卡内贡", title: "硬币怪兽", hp: 1020, atk: 138, def: 44, spd: 98, color: "#f9a825", image: "KANEGON.jpg", attackName: "硬币弹幕", attackPower: 1.58, special: { id: "coin_barrage", name: "硬币乱射", type: SKILL_TYPES.MULTI_HIT, target: TARGET_TYPES.ENEMY, power: 0.5, hits: 3, cooldown: 3, desc: "连续三次硬币攻击" } }),
  createExtraMonster({ id: "kaiju_nova", name: "诺瓦", title: "暗黑怪兽", hp: 1150, atk: 149, def: 43, spd: 90, color: "#ad1457", image: "NOVA.png", attackName: "黑暗弹", attackPower: 1.65, special: { id: "nova_rebirth", name: "黑暗复苏", type: SKILL_TYPES.REVIVE, target: TARGET_TYPES.DEAD_ALLY, power: 0.34, cooldown: 5, desc: "复活一名倒下的怪兽" } }),
  createExtraMonster({ id: "kaiju_mururoa", name: "穆鲁罗亚", title: "夜行怪兽", hp: 1190, atk: 148, def: 46, spd: 88, color: "#455a64", image: "MURUROA.jpg", attackName: "黑雾光线", attackPower: 1.65, special: { id: "night_fog", name: "夜雾侵蚀", type: SKILL_TYPES.POISON, target: TARGET_TYPES.ENEMY, power: 0.08, cooldown: 3, duration: 3, desc: "黑雾造成持续伤害" } }),
  createExtraMonster({ id: "kaiju_pagos", name: "帕戈斯", title: "地底怪兽", hp: 1270, atk: 150, def: 51, spd: 75, color: "#607d8b", image: "PAGOS.jpg", attackName: "放射能光线", attackPower: 1.7, special: { id: "pagos_heal", name: "地底能量恢复", type: SKILL_TYPES.HEAL_ALL, target: TARGET_TYPES.ALL_ALLIES, power: 0.22, cooldown: 4, desc: "恢复所有存活怪兽" } }),
  createExtraMonster({ id: "kaiju_redking_pair", name: "雷德王夫妇", title: "怪力组合", hp: 1380, atk: 162, def: 50, spd: 73, color: "#d84315", image: "RED KING (MALE) AND RED KING (FEMALE).jpg", attackName: "组合怪力投掷", attackPower: 1.8, special: { id: "pair_rampage", name: "双王乱斗", type: SKILL_TYPES.MULTI_HIT, target: TARGET_TYPES.ENEMY, power: 0.56, hits: 3, cooldown: 3, desc: "怪力三连击" } }),
  createExtraMonster({ id: "kaiju_seabozu", name: "西博佐", title: "宇宙怪兽", hp: 1160, atk: 144, def: 48, spd: 82, color: "#b0bec5", image: "SEABOZU.jpg", attackName: "白雾冲击", attackPower: 1.62, special: { id: "seabozu_revive", name: "白雾群体复苏", type: SKILL_TYPES.REVIVE_ALL, target: TARGET_TYPES.ALL_DEAD_ALLIES, power: 0.24, cooldown: 6, desc: "复活所有倒下的怪兽" } }),
  createExtraMonster({ id: "kaiju_verokron", name: "维克隆", title: "导弹超兽", hp: 1290, atk: 153, def: 51, spd: 79, color: "#c62828", image: "VEROKRON.png", attackName: "火箭弹", attackPower: 1.72, special: { id: "verokron_salvo", name: "全弹发射", type: SKILL_TYPES.DAMAGE_ALL, target: TARGET_TYPES.ALL_ENEMIES, power: 0.61, cooldown: 4, desc: "火箭弹攻击全体" } })
);

/**
 * 深拷贝角色模板为战斗单位
 * @param {Object} template
 * @param {string} uid
 */
function createFighter(template, uid) {
  return {
    uid,
    templateId: template.id,
    name: template.name,
    title: template.title,
    side: template.side,
    maxHp: template.maxHp,
    hp: template.maxHp,
    baseAtk: template.atk,
    baseDef: template.def,
    atk: template.atk,
    def: template.def,
    spd: template.spd,
    color: template.color,
    image: template.image,
    alive: true,
    buffs: [],
    skills: template.skills.map((s) => ({
      ...s,
      currentCd: 0,
    })),
  };
}

/**
 * 随机挑选 n 个不重复怪兽
 * @param {number} n
 */
function pickRandomMonsters(n = 3) {
  const pool = [...MONSTER_ROSTER];
  for (let i = pool.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, n).map((m, idx) => createFighter(m, `m${idx + 1}`));
}

/**
 * 根据 id 列表创建奥特曼小队
 * @param {string[]} ids
 */
function createHeroTeam(ids) {
  return ids.map((id, idx) => {
    const template = HERO_ROSTER.find((h) => h.id === id);
    if (!template) throw new Error(`未知奥特曼: ${id}`);
    return createFighter(template, `h${idx + 1}`);
  });
}

window.GameData = {
  SKILL_TYPES,
  TARGET_TYPES,
  HERO_ROSTER,
  MONSTER_ROSTER,
  createFighter,
  pickRandomMonsters,
  createHeroTeam,
};
